### ISSUE TITLE
Postfixes instead of libra operators

### ISSUE THREAD

**Issue by alabamenhu** [p6steve/raku-Physics-Measure#14]
The idea of the libra operator is interesting, but I think particularly for this type of a module where the information is fairly simple (that is, /<digit>+ <alpha>+/), using postfixes might work better on top of being more easily typed (or at least as an addition).  See https://codereview.stackexchange.com/questions/159150/mass-and-length-calculator-using-perl-6-custom-operator/227804#227804 for an example.

If you're ammenable to it, I'd be happy to work it up and submit a pull request.

**Comment by p6steve** [comment]
hi @alabamenhu - I think that the new module UnitPostfix does what you have in mind - you may have to go in and uncomment if you want all SI units (~30) xx all Prefixes (~20) - I have clipped these for performance reasons...
