### ISSUE TITLE
raku-Physics-Measure-Jupyter not starting

### ISSUE THREAD

**Issue by IlRoccOne** [p6steve/raku-Physics-Measure#30]
When accessing https://mybinder.org/v2/gh/p6steve/raku-Physics-Measure-Jupyter/master the Jupyter Notebook is not showing up.

**Comment by p6steve** [comment]
Hi @IlRoccOne - thank you for trying [https://github.com/p6steve/raku-Physics-Measure-Jupyter](https://github.com/p6steve/raku-Physics-Measure-Jupyter) - I really like the concept of Jupyter Binder, but the start time is very long for Binders images that are only rarely hit and that makes it unsuitable as one of the recommended consume options for my modules. For now, I have removed the Binder option from the installation instructions and advise you to do a local machine install of jupyter-notebook.

I do plan to get Binder working again for the Physics::Measure world - but currently working on v0.0.4 ... if this is a showstopper for you please let me know the situation ...
