### ISSUE TITLE
Does not install on Mac, with raku version 2022.3

### ISSUE THREAD

**Issue by sdondley** [p6steve/raku-Physics-Measure#53]
> $ zef --verbose install Physics::Measure
===> Searching for: Physics::Measure
===> Found: Physics::Measure:ver<1.0.5>:auth<zef:p6steve>:api<1> [via Zef::Repository::Ecosystems<fez>]
===> Searching for missing dependencies: Physics::Unit, Physics::Error
===> Found dependencies: Physics::Error:ver<0.1.1>:auth<zef:p6steve>:api<1>, Physics::Unit:ver<1.1.9>:auth<zef:p6steve>:api<1> [via Zef::Repository::Ecosystems<fez>]
===> Searching for missing dependencies: SVG, SVG::Plot
===> Found dependencies: SVG::Plot, SVG [via Zef::Repository::Ecosystems<p6c>]
===> Searching for missing dependencies: XML::Writer
===> Found dependencies: XML::Writer [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Physics::Measure:ver<1.0.5>:auth<zef:p6steve>:api<1> to /Users/stevedondley/.zef/tmp/1654343335.25217.1668.456363682831/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz
===> Fetching [OK]: Physics::Unit:ver<1.1.9>:auth<zef:p6steve>:api<1> to /Users/stevedondley/.zef/tmp/1654343335.25217.757.8403821563973/b4a3a245c4ed42d15089f263514b2a61db91ffc4.tar.gz
===> Fetching [OK]: Physics::Error:ver<0.1.1>:auth<zef:p6steve>:api<1> to /Users/stevedondley/.zef/tmp/1654343335.25217.6759.642564553906/f83a8dfe57695e4855f7d79ef94b07714d139108.tar.gz
===> Fetching [OK]: SVG to /Users/stevedondley/.zef/tmp/1654343335.25217.7283.084125426776/svg.git
===> Fetching [OK]: SVG::Plot to /Users/stevedondley/.zef/tmp/1654343335.25217.8532.353125146228/svg-plot.git
===> Fetching [OK]: XML::Writer to /Users/stevedondley/.zef/tmp/1654343335.25217.4940.226940977098/xml-writer.git
===> Extraction [OK]: Physics::Measure to /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz
===> Extraction [OK]: Physics::Error to /Users/stevedondley/.zef/tmp/f83a8dfe57695e4855f7d79ef94b07714d139108.tar.gz
===> Extraction [OK]: Physics::Unit to /Users/stevedondley/.zef/tmp/b4a3a245c4ed42d15089f263514b2a61db91ffc4.tar.gz
===> Extraction [OK]: SVG::Plot to /Users/stevedondley/.zef/tmp/svg-plot.git
===> Extraction [OK]: SVG to /Users/stevedondley/.zef/tmp/svg.git
===> Extraction [OK]: XML::Writer to /Users/stevedondley/.zef/tmp/xml-writer.git
===> Testing: XML::Writer
[XML::Writer] t/escaping.t ... ok
[XML::Writer] t/structure.t .. ok
[XML::Writer] All tests successful.
[XML::Writer] Files=2, Tests=11,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.86 cusr  0.09 csys =  0.97 CPU)
[XML::Writer] Result: PASS
===> Testing [OK] for XML::Writer
===> Testing: SVG
[SVG] t/basics.t .. ok
[SVG] All tests successful.
[SVG] Files=1, Tests=3,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.44 cusr  0.04 csys =  0.49 CPU)
[SVG] Result: PASS
===> Testing [OK] for SVG
===> Testing: SVG::Plot
[SVG::Plot] t/series.t .. ok
[SVG::Plot] t/ticks.t ... ok
[SVG::Plot] All tests successful.
[SVG::Plot] Files=2, Tests=10,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.79 cusr  0.09 csys =  0.90 CPU)
[SVG::Plot] Result: PASS
===> Testing [OK] for SVG::Plot
===> Testing: Physics::Unit:ver<1.1.9>:auth<zef:p6steve>:api<1>
[Physics::Unit] t/01-tst.t ....... ok
[Physics::Unit] t/02-dim.t ....... ok
[Physics::Unit] t/99-testMETA.t .. ok
[Physics::Unit] All tests successful.
[Physics::Unit] Files=3, Tests=34, 14 wallclock secs ( 0.01 usr  0.01 sys + 15.51 cusr  0.42 csys = 15.95 CPU)
[Physics::Unit] Result: PASS
===> Testing [OK] for Physics::Unit:ver<1.1.9>:auth<zef:p6steve>:api<1>
===> Testing: Physics::Error:ver<0.1.1>:auth<zef:p6steve>:api<1>
[Physics::Error] t/00-sanity.t .... ok
[Physics::Error] t/99-testMETA.t .. ok
[Physics::Error] All tests successful.
[Physics::Error] Files=2, Tests=7,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.69 cusr  0.08 csys =  0.79 CPU)
[Physics::Error] Result: PASS
===> Testing [OK] for Physics::Error:ver<0.1.1>:auth<zef:p6steve>:api<1>
===> Testing: Physics::Measure:ver<1.0.5>:auth<zef:p6steve>:api<1>
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in block <unit> at t/01-new.t line 23
[Physics::Measure] # You planned 21 tests, but ran 5
[Physics::Measure] t/01-new.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 16/21 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/02-asn.t line 17
[Physics::Measure] # You planned 11 tests, but ran 3
[Physics::Measure] t/02-asn.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 8/11 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/03-add.t line 14
[Physics::Measure] t/03-add.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 26/26 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/04-uni.t line 31
[Physics::Measure] # You planned 37 tests, but ran 7
[Physics::Measure] t/04-uni.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 30/37 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/05-cvt.t line 13
[Physics::Measure] t/05-cvt.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 52/52 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/06-com.t line 12
[Physics::Measure] t/06-com.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 37/37 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/07-ugg.t line 10
[Physics::Measure] t/07-ugg.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 39/39 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/08-syn.t line 13
[Physics::Measure] t/08-syn.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 12/12 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/09-cmp.t line 10
[Physics::Measure] t/09-cmp.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 14/14 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/10-sap.t line 10
[Physics::Measure] t/10-sap.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 19/19 subtests
[Physics::Measure] t/11-pwr.t ....... ok
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/12-uax.t line 47
[Physics::Measure] # You planned 22 tests, but ran 17
[Physics::Measure] t/12-uax.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 5/22 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/13-nrm.t line 26
[Physics::Measure] # You planned 6 tests, but ran 3
[Physics::Measure] t/13-nrm.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 3/6 subtests
[Physics::Measure] Type check failed in assignment to $!error; expected Physics::Error::Error but got Bool (Bool::False)
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 54
[Physics::Measure]   in method new at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 66
[Physics::Measure]   in sub prefix:<♎️> at /Users/stevedondley/.zef/tmp/4419122c24a1a93fe1d5f391a12beccf93c406b6.tar.gz/dist/lib/Physics/Measure.rakumod (Physics::Measure) line 562
[Physics::Measure]   in block <unit> at t/14-err.t line 53
[Physics::Measure] # You planned 16 tests, but ran 2
[Physics::Measure] t/14-err.t .......
[Physics::Measure] Dubious, test returned 255 (wstat 65280, 0xff00)
[Physics::Measure] Failed 14/16 subtests
[Physics::Measure] t/99-testMETA.t .. ok
[Physics::Measure] Test Summary Report
[Physics::Measure] -------------------
[Physics::Measure] t/01-new.t     (Wstat: 65280 Tests: 5 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 21 tests but ran 5.
[Physics::Measure] t/02-asn.t     (Wstat: 65280 Tests: 3 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 11 tests but ran 3.
[Physics::Measure] t/03-add.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 26 tests but ran 0.
[Physics::Measure] t/04-uni.t     (Wstat: 65280 Tests: 7 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 37 tests but ran 7.
[Physics::Measure] t/05-cvt.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 52 tests but ran 0.
[Physics::Measure] t/06-com.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 37 tests but ran 0.
[Physics::Measure] t/07-ugg.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 39 tests but ran 0.
[Physics::Measure] t/08-syn.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 12 tests but ran 0.
[Physics::Measure] t/09-cmp.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 14 tests but ran 0.
[Physics::Measure] t/10-sap.t     (Wstat: 65280 Tests: 0 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 19 tests but ran 0.
[Physics::Measure] t/12-uax.t     (Wstat: 65280 Tests: 17 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 22 tests but ran 17.
[Physics::Measure] t/13-nrm.t     (Wstat: 65280 Tests: 3 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 6 tests but ran 3.
[Physics::Measure] t/14-err.t     (Wstat: 65280 Tests: 2 Failed: 0)
[Physics::Measure]   Non-zero exit status: 255
[Physics::Measure]   Parse errors: Bad plan.  You planned 16 tests but ran 2.
[Physics::Measure] Files=15, Tests=43, 36 wallclock secs ( 0.04 usr  0.03 sys + 42.20 cusr  1.74 csys = 44.01 CPU)
[Physics::Measure] Result: FAIL
===> Testing [FAIL]: Physics::Measure:ver<1.0.5>:auth<zef:p6steve>:api<1>
Aborting due to test failure: Physics::Measure:ver<1.0.5>:auth<zef:p6steve>:api<1> (use --force-test to override)

**Comment by p6steve** [comment]
Hi @sdondley - apologies for this - I think that this is the error that was fixed 19 days ago - but the fix only seems to have made it to p6c and not the zef repo. https://raku.land/?q=Physics%3A%3AMeasure 

I have just bumped the fixed version to v1.0.6 and uploaded the new one to the zef repo. That should work as soon as it is reindexed. Meantime you can go ```zef --verbose install https://github.com/p6steve/raku-Physics-Measure.git``` right away.
